# Branches that trigger a build on commit
trigger:
- master
- feature/*

# Branches that trigger builds on PR
pr:
- master
- feature/*

jobs:

- job: Format
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 8
    matrix:
      format:
        _repo: "https://github.com/dotnet/format"
        _repoName: "dotnet/format"
        _sha: "686fc1efbe07d0a2d47147e36677ffcb09a74edc"
      roslyn:
        _repo: "https://github.com/dotnet/roslyn"
        _repoName: "dotnet/roslyn"
        _sha: "686fc1efbe07d0a2d47147e36677ffcb09a74edc"
      sdk:
        _repo: "https://github.com/dotnet/sdk"
        _repoName: "dotnet/sdk"
        _sha: "d03f6695c294a7c0dd4d46a292e650b7a6f6b667"
      project-system:
        _repo: "https://github.com/dotnet/project-system"
        _repoName: "dotnet/project-system"
        _sha: "e7baa11d85b75c1871e866c240ca4aa4240d7818"
      msbuild:
        _repo: "https://github.com/Microsoft/msbuild"
        _repoName: "Microsoft/msbuild"
        _sha: "a936b97e30679dcea4d99c362efa6f732c9d3587"
      blazor:
        _repo: "https://github.com/aspnet/blazor"
        _repoName: "aspnet/blazor"
        _sha: "cc449601d638ffaab58ae9487f0fd010bb178a12"
      efcore:
        _repo: "https://github.com/dotnet/efcore"
        _repoName: "dotnet/efcore"
        _sha: "0afeb9279ca72d0a5aa6738adf902fe6a30ba5c4"
      ef6:
        _repo: "https://github.com/dotnet/ef6"
        _repoName: "dotnet/ef6"
        _sha: "603c30382a5aec6677b4d90043694ac412cbb426"
  timeoutInMinutes: 20
  steps:
    - script: eng\integration-test.cmd -repo '$(_repo)' -sha '$(_sha)' -testPath '$(Build.SourcesDirectory)\temp' -stage 'prepare'
      displayName: Prepare $(_repoName) for formatting

    - script: eng\integration-test.cmd -repo '$(_repo)' -sha '$(_sha)' -testPath '$(Build.SourcesDirectory)\temp' -stage 'format-workspace'
      displayName: Run dotnet-format on $(_repoName) solution files

    - script: eng\integration-test.cmd -repo '$(_repo)' -sha '$(_sha)' -testPath '$(Build.SourcesDirectory)\temp' -stage 'format-folder'
      displayName: Run dotnet-format on $(_repoName) repo folder